version: '2'
services:
  redis:
    image: redislabs/redisgraph:edge
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
     - "7474:7474"
     - "7373:7373"
     - "7687:7687"